= The Dangerous and Thrilling Documentation Chronicles
Kismet Chameleon <kismet@asciidoctor.org>
:revnumber: 1.0 
:revdate: 10-02-2013
:revremark: The first incarnation of {doctitle} 
:doctype: book
:sectnums:
:toc: preamble

This journey begins on a bleary Monday morning.
Our intrepid team is in desperate need of double shot mochas, but the milk expired eight days ago.
A trip to the dairy was out of the question.
On Friday night, a mutant, script-injecting warlock had infected the Shetland cattle herd with a ravenous craving for tags and annotations.
The security wolves were at a trust building retreat in Katchanga, and no one in the village could locate their defensive operations manual.

Weak daylight trickled across the stripped pasture, chased by distant bovine screams...

[colophon]
= Colophon

Version: {revnumber}

Version Date: {revdate}

Version Notes: {revremark}

The Asciidoctor Press, Ceres and Denver

(C) 2018 by The Asciidoctor Press

Published in the Milky Way Galaxy

This book is designed by Dagger Flush, Denver, Colorado.
The types are handset Chinchilla and Dust, designed by Leeloo.
Leeloo designed the typefaces to soften the bluntness of documentation.
Created in Asciidoctor and Fedora 27.
The printing and binding is by Ceres Lithographing, Inc., Ceres, Milky Way.

[preface]
= Documentation Preface

The basis for this documentation germinated when I awoke one morning and was confronted by the dark and stormy eyes of the chinchilla.
She had conquered the mountain of government reports that, over the course of six months, had eroded into several minor foothills and a creeping alluvial plain of loose papers.

=== Acknowledgments in Preface

I'd like to thank the Big Bang and String Theory.
Would we be without them?

= Title of Part 1

[partintro]
.Optional part introduction title
--
This is the introduction to the first part of our mud-encrusted journey.
--

== Chapter 1

[abstract]
.Optional Abstract Title
--
This article will take you on a wonderful adventure of knowledge.

You'll start with the basics.
Beyond that, where you go is up to you.
--

There was mud...

== Chapter 2

Great gobs of mud...

[glossary]
== Part 1 Glossary

[glossary]
mud:: wet, cold dirt

= Part 2

[preface]
== Part 2 Preface

This part was written because...

== Chapter 1

The mud had turned to cement...

The hail-and-rainbow protocol can be initiated at five levels: double, tertiary, supernumerary, supermassive, and apocalyptic party.footnote:[The double hail-and-rainbow level makes my toes tingle.]   
A bold statement!footnoteref:[disclaimer,Opinions are my own.]   

Another outrageous statement.footnoteref:[disclaimer] 

[appendix]
= First Appendix

=== Appendix First Section

Qwerty.

=== Appendix Second Section

Asdfg.

[appendix]
= Second Appendix

Poiuyt.

