= Codex
Rafael Lorandi <coolparadox@gmail.com>
:doctype: book
:sectnums:
:toc: left
:revnumber: 0.0
:revdate: 09-08-2018
:revremark: Scratching phase

////
Remove following style defs when performed by weaving:
////

++++
<style>
code.codex{word-spacing:unset;padding:unset;background-color:unset}
span.codex{opacity:.5}
table.codex{background:unset;border:unset}
tr:nth-child(even).codex{background:unset}
tr:nth-child(odd).codex{background:unset}
td.codex_filelineid{line-height:unset;padding:unset;text-align:right;opacity:.2;padding-right:.5em}
td.codex_filecontent{line-height:unset;padding:unset}
a.codex_filechunkref{text-decoration:none;opacity:.5}
</style>
++++

Codex is a literate programming tool for asciidoc documentation format.

The literate programming paradigm enforces indirection layers on top of computer source code
in order to support expression of its logic in ways more suited to human thinking
instead of machine demanded order.

Asciidoc is a plain text, human readable document format, semantically equivalent to DocBook,
but using lightweight markup conventions.

[colophon]
= Colophon

Version: {revnumber}

Version Date: {revdate}

Version Notes: {revremark}

Codex is a literate programming tool for asciidoc documentation format. +
Copyright (C) 2018 Rafael Lorandi

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

[preface]
= Preface

By mid 2018, a search for literate programming for asciidoc leaded exclusively to
https://sourceforge.net/projects/eweb/[eWEB - literate programming in AsciiDoc] by Filippo Negroni.
eWEB 9.10 (current version at the time) offers _etangle.py_,
a tangler that recognizes code chunks embedded in asciidoc listing blocks.
Since input files to the tangler are already asciidoc compliant documents,
no weaver is deemed to be necessary.

eWEB served as a source of inspiration for Codex.

include::user_guide.adoc[]

////
///include
system_specification.adoc
////

:sectnums!:
[appendix]
include::license.adoc[]
