= Codedoc
Rafael Lorandi <coolparadox@gmail.com>
:doctype: book
:sectnums:
:toc: left
:revnumber: 0.0
:revdate: 09-08-2018
:revremark: Scratching phase
:codedoc:

////
Remove following style defs when performed by weaving:
////

++++
<style>
code.codedoc{word-spacing:unset;padding:unset;background-color:unset}
span.codedoc{opacity:.5}
table.codedoc{background:unset;border:unset}
tr:nth-child(even).codedoc{background:unset}
tr:nth-child(odd).codedoc{background:unset}
td.codedoc_filelineid{line-height:unset;padding:unset;text-align:right;opacity:.2;padding-right:.5em}
td.codedoc_filecontent{line-height:unset;padding:unset}
a.codedoc_filechunkref{text-decoration:none;opacity:.5}
</style>
++++

Codedoc is a literate programming tool for asciidoc documentation format.

The literate programming paradigm enforces indirection layers on top of computer source code
in order to support expression of its logic in ways more suited to human thinking
instead of machine demanded order.

Asciidoc is a plain text, human readable document format, semantically equivalent to DocBook,
but using lightweight markup conventions.

[colophon]
= Colophon

Version: {revnumber}

Version Date: {revdate}

Version Notes: {revremark}

Codedoc is a literate programming tool for asciidoc documentation format. +
Copyright (C) 2018 Rafael Lorandi

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

[preface]
= Preface

By mid 2018, a search for literate programming for asciidoc leaded exclusively to
https://sourceforge.net/projects/eweb/[eWEB - literate programming in AsciiDoc] by Filippo Negroni.
eWEB 9.10 (current version at the time) offers _etangle.py_,
a tangler that recognizes code chunks embedded in asciidoc listing blocks.
Since input files to the tangler are already asciidoc compliant documents,
no weaver is deemed to be necessary.

eWEB served as a source of inspiration for Codedoc.

= User Guide

== Codedoc by Examples

Codedoc is a preprocessor for asciidoc documentation
that recognizes asciidoc comment blocks containing predefined content as pieces of source code.
Codedoc is designed to serve as a tool for literate programming.

This is more easily explained by examples.

=== Code Files

Say the following appears anywhere in an asciidoc document:

....
////
//hello.c
#include <stdio.h>
int main() {
    printf("Hello world!\n");
    return 0;
}
////
....

Note that the first content line starts with `//`
followed by a file name 
(in this case file hello.c in a flat directory,
but you can name files under subdirectories as well).
Further lines of the block contain the source code of hello.c.

If you process the asciidoc document directly,
the above block is ignored as `////` delimits a comment block in asciidoc syntax.
Running *codedoc* instead over the asciidoc document however produces two outcomes:

. A processed version of the asciidoc document that renders this block as:
footnote:[Only HTML backend is currently supported.]
+
.hello.c
[#hello_c_1]
++++
<div id="hello_c_1" class="exampleblock" style="margin-bottom:1.25em;">
<div class="title">hello.c</div>
<div class="content" style="margin-bottom:.5em;">
<code class="codedoc">#include &lt;stdio.h&gt;</code><span class="codedoc">&crarr;</span><br>
<code class="codedoc">int main() {</code><span class="codedoc">&crarr;</span><br>
<code class="codedoc">&nbsp;&nbsp;&nbsp;&nbsp;printf("Hello world!\n");</code><span class="codedoc">&crarr;</span><br>
<code class="codedoc">&nbsp;&nbsp;&nbsp;&nbsp;return 0;</code><span class="codedoc">&crarr;</span><br>
<code class="codedoc">}</code><span class="codedoc">&crarr;</span><br>
</div>
</div>
++++
+
This block is named by anchor _#hello_c_1_,
allowing references from anywhere in the processed document: <<hello_c_1>>

. File _hello.c_ in filesystem containing:
+
....
#include <stdio.h>
int main() {
    printf("Hello world!\n");
    return 0;
}
....

Blocks of code file therefore allow the documentation of a software project
to be the primary source of its source code.

=== Code Chunks

There is no real gain in
bringing whole source files to the realm of a document
only to extract them in a preprocessing step afterwards.

Things get more interesting when chunks of code are introduced.
As the name implies, blocks of code chunk are named fragments of source code.

For instance, we know that the source of hello program has
a section for inclusion of required language libraries, say:

....
////
/hello includes
#include <stdio.h>
////
....

Also, every C program has the main() function:

....
////
/hello main
int main() {
    /greet the world
    return 0;
}
////
....

Finally, let's consider that
the main business of hello is to greet the world in an objective and profound way:

....
////
/greet the world
printf("Hello world!\n");
////
....

(As you may have guessed,
codedoc understands a comment block
whose first content line contains a single leading `/`
as a code chunk.)

Given the above chunks anywhere in the document,
_hello.c_ could then be defined as the following block of code file:

....
////
//hello.c
/hello includes
/hello main
////
....

Now *codedoc* generates a processed version of the asciidoc document
that renders these blocks as the following:

.hello includes
[#hello_includes_1]
++++
<div id="hello_includes_1" class="exampleblock" style="margin-bottom:1.25em;">
<div class="title">hello includes</div>
<div class="content" style="margin-bottom:.5em;">
<code class="codedoc">#include &lt;stdio.h&gt;</code><span class="codedoc">&crarr;</span><br>
</div>
<div class="title"><sup>
Used by: <a href="#hello_c_2">hello.c</a>.
</sup></div>
</div>
++++

.hello main
[#hello_main_1]
++++
<div id="hello_main_1" class="exampleblock" style="margin-bottom:1.25em;">
<div class="title">hello main</div>
<div class="content" style="margin-bottom:.5em;">
<code class="codedoc">int main() {</code><span class="codedoc">&crarr;</span><br>
<code class="codedoc">&nbsp;&nbsp;&nbsp;&nbsp;</code><em><a href="#greet_the_world_1">greet the world</a></em><br>
<code class="codedoc">&nbsp;&nbsp;&nbsp;&nbsp;return 0;</code><span class="codedoc">&crarr;</span><br>
<code class="codedoc">}</code><span class="codedoc">&crarr;</span><br>
</div>
<div class="title"><sup>
Used by: <a href="#hello_c_2">hello.c</a>.
</sup></div>
</div>
++++

.greet the world
[#greet_the_world_1]
++++
<div id="greet_the_world_1" class="exampleblock" style="margin-bottom:1.25em;">
<div class="title">greet the world</div>
<div class="content" style="margin-bottom:.5em;">
<code class="codedoc">printf("Hello world!\n");</code><span class="codedoc">&crarr;</span><br>
</div>
<div class="title"><sup>
Used by: <a href="#hello_main_1">hello main</a>.
</sup></div>
</div>
++++

.hello.c
[#hello_c_2]
++++
<div id="hello_c_2" class="exampleblock" style="margin-bottom:1.25em;">
<div class="title">hello.c</div>
<div class="content" style="margin-bottom:.5em;">
<em><a href="#hello_includes_1">hello includes</a></em><br>
<em><a href="#hello_main_1">hello main</a></em><br>
</div>
</div>
++++

Same as before, file _hello.c_ is generated in filesystem
containing the result of recursively de-referencing
(and properly indenting) its chunks:

....
#include <stdio.h>
int main() {
    printf("Hello world!\n");
    return 0;
}
....

There is no requirement as to
the order by which chunk and file blocks are defined within the document --
you are free to reference chunks defined later in the document as well,
if you decide it suits better the explanation flow of your documentation.

Code chunks support a powerful concept in literate programming, namely that
software programs should be considered works of literature.
Therefore you cannot properly document software if you are restricted
to the order imposed by machine understandable entities (like functions and methods)
in the sense an underlying idea of a given software
is usually splattered along its code base in several places and files.

=== Chunk Continuation

A given code chunk (or file) may appear splitted along an asciidoc document,
and codedoc will happily consider them as the same unit.

For instance, let's add a complement to the greeting of last chapter:

....
////
/greet the world
printf("It's a beautiful day.\n");
////
....

Now we have the following rendering:

.hello includes
[#hello_includes_2]
++++
<div id="hello_includes_2" class="exampleblock" style="margin-bottom:1.25em;">
<div class="title">hello includes</div>
<div class="content" style="margin-bottom:.5em;">
<code class="codedoc">#include &lt;stdio.h&gt;<span class="codedoc">&crarr;</span></code><br>
</div>
<div class="title"><sup>
Used by: <a href="#hello_c_3">hello.c</a>.
</sup></div>
</div>
++++

.hello main
[#hello_main_2]
++++
<div id="hello_main_2" class="exampleblock" style="margin-bottom:1.25em;">
<div class="title">hello main</div>
<div class="content" style="margin-bottom:.5em;">
<code class="codedoc">int main() {<span class="codedoc">&crarr;</span></code><br>
<code class="codedoc">&nbsp;&nbsp;&nbsp;&nbsp;</code><em><a href="#greet_the_world_2">greet the world</a></em><br>
<code class="codedoc">&nbsp;&nbsp;&nbsp;&nbsp;return 0;<span class="codedoc">&crarr;</span></code><br>
<code class="codedoc">}<span class="codedoc">&crarr;</span></code><br>
</div>
<div class="title"><sup>
Used by: <a href="#hello_c_3">hello.c</a>.
</sup></div>
</div>
++++

.greet the world (1 of 2)
[#greet_the_world_2]
++++
<div id="greet_the_world_2" class="exampleblock" style="margin-bottom:1.25em;">
<div class="title">greet the world (1 of 2)</div>
<div class="content" style="margin-bottom:.5em;">
<code class="codedoc">printf("Hello world!\n");<span class="codedoc">&crarr;</span></code><br>
</div>
<div class="title"><sup>
Next: <a href="#greet_the_world_3">greet the world (2 of 2)</a>.
Used by: <a href="#hello_main_2">hello main</a>.
</sup></div>
</div>
++++

.hello.c
[#hello_c_3]
++++
<div id="hello_c_3" class="exampleblock" style="margin-bottom:1.25em;">
<div class="title">hello.c</div>
<div class="content" style="margin-bottom:.5em;">
<em><a href="#hello_includes_2">hello includes</a></em><br>
<em><a href="#hello_main_2">hello main</a></em><br>
</div>
</div>
++++

.greet the world (2 of 2)
[#greet_the_world_3]
++++
<div id="greet_the_world_3" class="exampleblock" style="margin-bottom:1.25em;">
<div class="title">greet the world (2 of 2)</div>
<div class="content" style="margin-bottom:.5em;">
<code class="codedoc">printf("It's a beautiful day.\n");<span class="codedoc">&crarr;</span></code><br>
</div>
<div class="title"><sup>
Previous: <a href="#greet_the_world_2">greet the world (1 of 2)</a>.
Used by: <a href="#hello_main_2">hello main</a>.
</sup></div>
</div>
++++

And the generated hello.c file becomes:

....
#include <stdio.h>
int main() {
    printf("Hello world!\n");
    printf("It's a beautiful day.\n");
    return 0;
}
....

Continuation of code chunks eases all related pieces of source code
to be gathered into a single place of the software documentation, 
for then to be explained in a way more palatable to humans.

[quote, Donald Knuth, Introducer of the literate programming paradigm]
Instead of imagining that our main task is to instruct a computer what to do,
let us concentrate rather on explaining to human beings what we want a computer to do.

=== Special Directives

Besides code files and code chunks,
codedoc recognizes asciidoc comment blocks containing
a few single line directives.

==== Table of Chunks

Lists all chunks of the document.

....
////
///table_of_chunks
////
....

Produces something like:

++++
<div id="toc" class="toc">
<div id="toctitle" class="title">Table of Chunks</div>
<ul class="sectlevel1">
<li><a href="#hello_includes_2">hello includes</a></li>
<li><a href="#hello_main_2">hello main</a></li>
<li><a href="#greet_the_world_2">greet the world (1 of 2)</a></li>
<li><a href="#hello_c_3">hello.c</a></li>
<li><a href="#greet_the_world_3">greet the world (2 of 2)</a></li>
<li><a href="#"></a></li>
</ul>
</div>
++++

==== Exploded Code

....
////
///exploded_code
////
....

Produces:

. A table of code files;
. One level 3 chapter after each code file containing its full listing with all chunks dereferenced.

Sample:

++++
<div id="toc" class="toc">
<div id="toctitle" class="title">Table of Files</div>
<ul class="sectlevel1">
<li><a href="#file_hello_c">hello.c</a></li>
</ul>
</div>
++++

[#file_hello_c]
[discrete]
=== hello.c

_[small]#Origin chunk: <<hello_c_3>>#_

++++
<div class="exampleblock" style="margin-bottom:1.25em;">
<div class="content" style="margin-bottom:.5em;">
<table class="codedoc">
<tr class="codedoc"><td id="file_hello_c_line_1" class="codedoc_filelineid">1</td><td class="codedoc_filecontent"><code class="codedoc">#include &lt;stdio.h&gt;</code><span class="codedoc">&crarr;</span>&nbsp;<sub><em><a class="codedoc_filechunkref" href="#hello_includes_2">hello includes</a></em></sub></td></tr>
<tr class="codedoc"><td id="file_hello_c_line_2" class="codedoc_filelineid">2</td><td class="codedoc_filecontent"><code class="codedoc">int main() {</code><span class="codedoc">&crarr;</span>&nbsp;<sub><em><a class="codedoc_filechunkref" href="#hello_main_2">hello main</a></em></sub></td></tr>
<tr class="codedoc"><td id="file_hello_c_line_3" class="codedoc_filelineid">3</td><td class="codedoc_filecontent"><code class="codedoc">&nbsp;&nbsp;&nbsp;&nbsp;printf("Hello world!\n");</code><span class="codedoc">&crarr;</span>&nbsp;<sub><em><a class="codedoc_filechunkref" href="#greet_the_world_2">greet the world (1 of 2)</a></em></sub></td></tr>
<tr class="codedoc"><td id="file_hello_c_line_4" class="codedoc_filelineid">4</td><td class="codedoc_filecontent"><code class="codedoc">&nbsp;&nbsp;&nbsp;&nbsp;printf("It's a beautiful day.\n");</code><span class="codedoc">&crarr;</span>&nbsp;<sub><em><a class="codedoc_filechunkref" href="#greet_the_world_3">greet the world (2 of 2)</a></em></sub></td></tr>
<tr class="codedoc"><td id="file_hello_c_line_5" class="codedoc_filelineid">5</td><td class="codedoc_filecontent"><code class="codedoc">&nbsp;&nbsp;&nbsp;&nbsp;return 0;</code><span class="codedoc">&crarr;</span>&nbsp;<sub><em><a class="codedoc_filechunkref" href="#hello_main_2">hello main</a></em></sub></td></tr>
<tr class="codedoc"><td id="file_hello_c_line_6" class="codedoc_filelineid">6</td><td class="codedoc_filecontent"><code class="codedoc">}</code><span class="codedoc">&crarr;</span>&nbsp;<sub><em><a class="codedoc_filechunkref" href="#hello_main_2">hello main</a></em></sub></td></tr>
</table>
</div>
</div>
++++

Exploded code is fully cross referenced back to provider chunks.
Also, each line is uniquely anchored, allowing direct links: 
pass:[<a href="#file_hello_c_line_4">file_hello_c_line_4</a>]

== Installation

Great gobs of mud...

[glossary]
== Part 1 Glossary

[glossary]
mud:: wet, cold dirt

= Part 2

[preface]
== Part 2 Preface

This part was written because...

== Chapter 1

The mud had turned to cement...

The hail-and-rainbow protocol can be initiated at five levels: double, tertiary, supernumerary, supermassive, and apocalyptic party.footnote:[The double hail-and-rainbow level makes my toes tingle.]   
A bold statement!footnoteref:[disclaimer,Opinions are my own.]   

Another outrageous statement.footnoteref:[disclaimer] 

:sectnums!:
[appendix]
include::license.adoc[]
